apiVersion: apps/v1
kind: Deployment
metadata:
  name: page
  namespace: '{{.ns}}'
spec:
  selector:
    matchLabels:
      app: page
  template:
    metadata:
      labels:
        app: page
    spec:
      containers:
        - name: page
          image: k3env/landing-cv:{{.tag}}
          resources:
            limits:
              memory: '64Mi'
              cpu: '100m'
          ports:
            - containerPort: 80
